// Users
export const GET_USERS_REQUEST='GET_USERS_REQUEST';
export const GET_USERS_SUCCESS='GET_USERS_SUCCESS';
export const ADD_USER_REQUEST='ADD_USER_REQUEST';
export const DELETE_USER_REQUEST='DELETE_USER_REQUEST';

// Auth
export const SET_ACTIVE_USER='SET_ACTIVE_USER';


//Couter
export const INCREMENT_COUNTER='INCREMENT_COUNTER';