// Users
export const GET_USERS_REQUEST='GET_USERS_REQUEST';
export const GET_USERS_SUCCESS='GET_USERS_SUCCESS';
export const ADD_USER_REQUEST='ADD_USER_REQUEST';
export const DELETE_USER_REQUEST='DELETE_USER_REQUEST';

// Auth
export const SET_ACTIVE_USER='SET_ACTIVE_USER';


//Counter
export const INCREMENT_COUNTER='INCREMENT_COUNTER';
export const INCREMENT_COUNTER_ASYNC='INCREMENT_COUNTER_ASYNC';
export const ASYNC_INCREMENT_COUNTER='ASYNC_INCREMENT_COUNTER';
export const ASYNC_INCREMENT_COUNTER_DO='ASYNC_INCREMENT_COUNTER_DO';
export const INCREMENT_COUNTER_ASYNC_REQUEST='INCREMENT_COUNTER_ASYNC_REQUEST';
